force-app/main/default/objects/Animal__c/fields/URLtoFoto__c.field-meta.xml
<CustomField>
    <fullName>URLtoFoto__c</fullName>
    <label>URLtoFoto</label>
    <type>Url</type>
</CustomField>

force-app/main/default/classes/RestMissingAnimalImage.cls
@RestResource(urlMapping='/MissingAnimals/*')
global class RestMissingAnimalImage {
	@HttpGet
    global static String getMissingAnimalImage(){
        RestRequest request = RestContext.request;
        String animalId = request.requestURI.substring(
          request.requestURI.lastIndexOf('/')+1);
        Animal__c result = [SELECT Id, URLtoFoto__c  FROM Animal__c WHERE Id = :animalId];
        return result.URLtoFoto__c;
    }
}